from typing import Protocol
from pyglet.math import Vec2, Vec3
from arcade.types.numbers import AsFloat

class Shape2D(Protocol):
    x: AsFloat
    y: AsFloat
    left: AsFloat
    right: AsFloat
    top: AsFloat
    bottom: AsFloat
    width: AsFloat
    height: AsFloat

    @property
    def center(self) -> Vec2: ...
    @property
    def top_left(self) -> Vec2: ...
    @property
    def top_right(self) -> Vec2: ...
    @property
    def bottom_left(self) -> Vec2: ...
    @property
    def bottom_right(self) -> Vec2: ...
    @property
    def size(self) -> Vec2: ...

    def __contains__(self, point: Vec2) -> bool: ...
    def to_points(self) -> tuple[Vec2, ...]: ...
    def from_kwargs(self, **kwargs: AsFloat): ...

    @property
    def kwargs(self) -> dict[str, AsFloat]: ...

class Shape3D(Protocol):
    x: AsFloat
    y: AsFloat
    z: AsFloat
    left: AsFloat
    right: AsFloat
    top: AsFloat
    bottom: AsFloat
    near: AsFloat
    far: AsFloat
    width: AsFloat
    height: AsFloat
    depth: AsFloat

    @property
    def center(self) -> Vec3: ...
    @property
    def bottom_left_near(self) -> Vec3: ...
    @property
    def bottom_left_far(self) -> Vec3: ...
    @property
    def bottom_right_near(self) -> Vec3: ...
    @property
    def bottom_right_far(self) -> Vec3: ...
    @property
    def top_left_near(self) -> Vec3: ...
    @property
    def top_left_far(self) -> Vec3: ...
    @property
    def top_right_near(self) -> Vec3: ...
    @property
    def top_right_far(self) -> Vec3: ...
    @property
    def size(self) -> Vec3: ...

    def __contains__(self, point: Vec3) -> bool: ...
    def to_points(self) -> tuple[Vec3, ...]: ...
    def from_kwargs(self, **kwargs: AsFloat): ...

    @property
    def kwargs(self) -> dict[str, AsFloat]: ...

Shape = Shape2D | Shape3D
